### ISSUE TITLE
非常不错

### ISSUE THREAD

**Issue by avenwu** [panpf/switch-button#4]
赞，效果非常棒，唯一的小问题就是，涉及的图片必须都是图片，不能兼容xml写的shape等

**Comment by panpf** [comment]
我记得当初做的时候页考虑了xml drawable，貌似是由于xml drawable绘制的时候不支持Xfermode而不了了之，你也可以改改试试

**Comment by avenwu** [comment]
hi，刚提了一个request，请看一下，扩展xml shape支持，https://github.com/xiaopansky/SwitchButton/pull/5

**Comment by panpf** [comment]
已经合并了，谢谢你的提交！

**Comment by avenwu** [comment]
:+1:
