### ISSUE TITLE
按钮在手机看起来很小啊，怎么调大小的

### ISSUE THREAD

**Issue by lmdiloveu** [panpf/switch-button#6]
按钮在手机看起来很小啊，怎么调大小的

**Comment by panpf** [comment]
那是图片小了 换更大的图片

**Comment by lmdiloveu** [comment]
@xiaopansky 我自己切图吗？你这个点九的图不行吗！

**Comment by lmdiloveu** [comment]
解决了，谢谢。我把图片放到drawable-xhdpi目录就行了，放到drawable-xxhdpi目录不行

**Comment by panpf** [comment]
要么把图片放到更低的drawable文件夹下，让系统给放大，要么自己做一套更大的图，点9的需要在读到内存之后再设置更大的bounds
