### ISSUE TITLE
这个按钮怎么单独拿出来啊

### ISSUE THREAD

**Issue by lmdiloveu** [panpf/switch-button#7]
<me.xiaopan.switchbutton.SwitchButton>  直接在布局里面用，是包含左边的文字的，现在不需要文字，想直接用按钮就行，提供按钮切换监听即可

**Comment by panpf** [comment]
文字是CompoundButton的属性 你看下CompoundButton的API怎么去掉

**Comment by wisdomcai** [comment]
我导入的时候报错Error:(31, 13) Failed to resolve: me.xiaopan:switchbutton:lastVersionName，这是啥意思

**Comment by panpf** [comment]
lastVersionName要替换成真实的版本号

**Comment by wisdomcai** [comment]
谢谢，已经用上了

2017-03-03
________________________________
wisdomcai
________________________________
发件人：Flyge <notifications@github.com>
发送时间：2017-03-03 16:36
主题：Re: [xiaopansky/SwitchButton] 这个按钮怎么单独拿出来啊 (#7)
收件人："xiaopansky/SwitchButton"<SwitchButton@noreply.github.com>
抄送："wisdomcai"<wisdomcai@outlook.com>,"Comment"<comment@noreply.github.com>


Closed #7<https://github.com/xiaopansky/SwitchButton/issues/7>.

**Comment by wisdomcai** [comment]
如何把switchbutton的字体居中显示啊

2017-03-07
________________________________
wisdomcai
________________________________
发件人：Flyge <notifications@github.com>
发送时间：2017-03-03 16:35
主题：Re: [xiaopansky/SwitchButton] 这个按钮怎么单独拿出来啊 (#7)
收件人："xiaopansky/SwitchButton"<SwitchButton@noreply.github.com>
抄送："wisdomcai"<wisdomcai@outlook.com>,"Comment"<comment@noreply.github.com>


lastVersionName要替换成真实的版本号
