### ISSUE TITLE
字体能不能设置成居中显示？？？

### ISSUE THREAD

**Issue by wisdomcai** [panpf/switch-button#9]
因为项目需求，需要把字体放到button的正中央，可是我翻遍源码都找不到响应方法设置，也找不到跟蚊子相关的任何信息，如果您有时间，麻烦尽快回复一下，谢谢

**Comment by wisdomcai** [comment]
不管能不能，也给我个回信告知我一声好么？？？

**Comment by panpf** [comment]
不好意思啊  前几天没上班 出差了没及时查看issues。

目前没有直接的办法设置文字居中显示（讲真的你这需求有些奇特），不过可以采取曲线救国的办法，例如：
```xml
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <me.xiaopan.switchbutton.SwitchButton
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:frameDrawable="@drawable/switch_frame"
        app:sliderDrawable="@drawable/selector_switch_slider"
        app:stateDrawable="@drawable/selector_switch_state"
        app:stateMaskDrawable="@drawable/switch_state_mask" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingRight="80dp"
        android:text="新闻推送" />
</FrameLayout>
```
SwitchButton只用来显示开关图标，在单独用一个TextView显示文字，然后让文字横向居中

**Comment by wisdomcai** [comment]
谢谢，我也正打算这么做，想自己写一个switchbutton，但是没你的好看，还是用你的好看。

2017-03-13
________________________________
wisdomcai
________________________________
发件人：Flyge <notifications@github.com>
发送时间：2017-03-13 14:21
主题：Re: [xiaopansky/SwitchButton] 字体能不能设置成居中显示？？？ (#9)
收件人："xiaopansky/SwitchButton"<SwitchButton@noreply.github.com>
抄送："wisdomcai"<wisdomcai@outlook.com>,"Author"<author@noreply.github.com>


不好意思啊 前几天�没上班 出差了没及时查看issues。

目前没有直接的办法设置文字居中显示（讲真的你这需求有些奇特），不过可以采取曲线救国的办法，例如：

<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <me.xiaopan.switchbutton.SwitchButton
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:frameDrawable="@drawable/switch_frame"
        app:sliderDrawable="@drawable/selector_switch_slider"
        app:stateDrawable="@drawable/selector_switch_state"
        app:stateMaskDrawable="@drawable/switch_state_mask" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:paddingRight="80dp"
        android:text="新闻推送" />
</FrameLayout>

SwitchButton只用来显示开关图标，在单独用一个TextView显示文字，然后让文字�横向居中
